    // อุปกรณ์ทั่วไป (จาก Google Sheets + เดิม)
    { id: 'eq-gen-1', name: 'ถุงมือเบอร์ 6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-2', name: 'ถุงมือเบอร์ 6 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-3', name: 'ถุงมือเบอร์ 7', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-4', name: 'ถุงมือเบอร์ 7 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-5', name: 'ถุงมือเบอร์ 8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-6', name: 'ถุงมือเบอร์ 8 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-7', name: 'Nss 0.9% 100 ml.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-8', name: 'สี Sterile (Medical Dye)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-9', name: 'ใบมีด Dermatome', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-10', name: 'ใบมีด graft', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-11', name: 'Foley\'s cath 2 หาง No.6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-12', name: 'Foley\'s cath 2 หาง No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-13', name: 'Foley\'s cath 2 หาง No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-14', name: 'Foley\'s cath 2 หาง No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-15', name: 'Foley\'s cath 2 หาง No.14', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-16', name: 'Foley\'s cath 2 หาง No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-17', name: 'Foley\'s cath 2 หาง No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-18', name: 'Foley\'s cath 2 หาง No.20', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-19', name: 'Foley\'s cath 2 หาง No.22', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-20', name: 'Foley\'s cath 2 หาง No.24', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-21', name: 'Foley\'s cath 3 หาง No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-22', name: 'Foley\'s cath 3 หาง No.20', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-23', name: 'Foley\'s cath 3 หาง No.22', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-24', name: 'Cath แดง No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-25', name: 'Cath แดง No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-26', name: 'Cath แดง No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-27', name: 'Cath แดง No.14', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-28', name: 'Cath แดง No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-29', name: 'Cath แดง No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-30', name: 'Four wing No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-31', name: 'Four wing No.14', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-32', name: 'Four wing No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-33', name: 'Four wing No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-34', name: 'Four wing No.20', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-35', name: 'Four wing No.22', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-36', name: 'Four wing No.24', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-37', name: 'Four wing No.26', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-38', name: 'Four wing No.28', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-39', name: 'Four wing No.30', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-40', name: 'Silicone cath 2 หาง No.14', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-41', name: 'Silicone cath 2 หาง No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-42', name: 'Silicone cath 2 หาง No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-43', name: 'Feeding tube No.5', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-44', name: 'Feeding tube No.6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-45', name: 'Feeding tube No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-46', name: 'Feeding tube No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-47', name: 'NG. No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-48', name: 'NG. No.14', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-49', name: 'NG. No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-50', name: 'NG. No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-51', name: 'Thoracic cath No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-52', name: 'Thoracic cath No.20', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-53', name: 'Thoracic cath No.24', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-54', name: 'Thoracic cath No.28', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-55', name: 'Thoracic cath No.32', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-56', name: 'Thoracic cath No.36', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-57', name: 'Set I.V.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-58', name: 'สาย Bipolar สีฟ้า', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-59', name: 'สาย Bipolar Dual สีน้ำตาล', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-60', name: 'สายจี้ Foot', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-61', name: 'สายจี้ Hand', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-62', name: 'Merocel', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-63', name: 'Elastic sterile 3"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-64', name: 'Elastic sterile 4"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-65', name: 'Elastic sterile 6"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-66', name: 'Webril sterile 3"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-67', name: 'Webril sterile 4"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-68', name: 'Webril sterile 6"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-69', name: 'Prolene Mesh graft เล็ก', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-70', name: 'Prolene Mesh graft ใหญ่', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-71', name: 'Gauze drain 3/4 cm.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-72', name: 'Gauze drain 1.5 cm.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-73', name: 'Gauze Heart 3x9', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-74', name: 'Gauze Ortho', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-75', name: 'ขวด Vac Drain 200 ml.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-76', name: 'ขวด Vac Drain 600 ml.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-77', name: 'เข็ม Drain No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-78', name: 'เข็ม Drain No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-79', name: 'เข็ม Drain No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-80', name: 'สาย Redivac drain No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-81', name: 'สาย Redivac drain No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-82', name: 'สาย Redivac drain No.12', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-83', name: 'Jackson Pratt No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-84', name: 'Extension Tube', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-85', name: 'Penrose drain 1/2"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-86', name: 'Penrose drain 3/4"', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-87', name: 'Tube drain กลาง', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-88', name: 'Tube drain เล็ก', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-89', name: 'Wire Guide (PCNL)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-90', name: 'ชุดเข็มเจาะ (PCNL)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-91', name: 'PCN No.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-92', name: 'PCN No.10', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-93', name: 'DJ. Stent No.4.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-94', name: 'DJ. Stent No.6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-95', name: 'DJ. Stent No.7', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-96', name: 'Fogarty No.2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-97', name: 'Fogarty No.3', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-98', name: 'Fogarty No.4', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-99', name: 'Fogarty No.5', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-100', name: 'สาย RP No.3', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-101', name: 'สาย RP No.4', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-102', name: 'สาย RP No.5', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-103', name: 'สาย RP No.6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-104', name: 'Opsite 15x28 cm.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-105', name: 'Ioban 35x35 cm.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-106', name: 'Ioban 60x45 cm.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-107', name: 'Tegaderm เล็ก (เขียว)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-108', name: 'Tegaderm เล็ก+Pad (แดง)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-109', name: 'Tegaderm กลาง+Pad', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-110', name: 'Leukostrip', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-111', name: 'Spongostan', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-112', name: 'Sofra-tulle', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-113', name: 'Rack เข็ม Neuro', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-114', name: 'Rack เข็ม ศัลย์', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-115', name: 'Rack เข็ม Uro', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-116', name: 'Rack เข็ม สูติ', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-117', name: 'Rack เข็ม ตรง', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-118', name: 'Rack เข็ม เย็บข้าง', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-119', name: 'เข็ม Sterile 18 x 1 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-120', name: 'เข็ม Sterile 21 x 1 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-121', name: 'เข็ม Sterile 24 x 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-122', name: 'เข็ม Sterile 25 x 1', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-123', name: 'เข็ม Sterile 25 x 1 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-124', name: 'เข็ม Sterile 27 x 1', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-125', name: 'เข็ม Sterile 27 x 1/2', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-126', name: 'Raney Clip', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-127', name: 'Cottonoid No. L', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-128', name: 'Cottonoid No. M', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-129', name: 'Transfer bag neuro', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-130', name: 'Feeding tube No.8 neuro', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-131', name: 'Feeding tube No.10 neuro', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-132', name: 'Colostomy bag พ.ศรุตา', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-133', name: 'ถุงกล้อง', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-134', name: 'Tracheostomy tube No. 6', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-135', name: 'Tracheostomy tube No. 7', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-136', name: 'Tracheostomy tube No. 7.5', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-137', name: 'Tracheostomy tube No. 8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-138', name: 'Vein stripping', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-139', name: 'Syringe Insulin 1 cc.ถอดเข็ม', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-140', name: 'Syringe 3 cc.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-141', name: 'Syringe 5 cc. / 5 cc.ล็อค', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-142', name: 'Syringe 10 cc. / 10 cc.ล็อค', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-143', name: 'Syringe 20 cc.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-144', name: 'Syringe 50 cc.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-145', name: 'Pads Valleylab (สีฟ้า)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-146', name: 'Pads เด็ก Valleylab (สีฟ้า)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-147', name: 'Pads เด็ก Valleylab (สีน้ำเงิน)', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-148', name: 'Pads เด็ก ไม่มีสาย', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-149', name: 'Pads ผู้ใหญ่ ไม่มีสาย', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-150', name: 'Pads ผู้ใหญ่ มีสาย', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-151', name: 'ลวด No.16', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-152', name: 'ลวด No.18', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-153', name: 'ลวด No.20', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-154', name: 'ลวด No.22', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-155', name: 'ลวด No.23', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-156', name: 'ลวด No.24', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-157', name: 'ลวด No.25', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-158', name: 'ลวด No.26', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-159', name: 'ลวด No.28', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-160', name: 'ลวด No.30', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-161', name: 'Arch bar', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-162', name: 'ถุง burr hole', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-163', name: 'Urine bag', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-164', name: 'D.S.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-165', name: 'Culture', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-166', name: 'Skin Staple', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-167', name: 'ตัว off staple', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-168', name: 'Vascular loop เล็ก-ใหญ่', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-169', name: 'Vaseline', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-170', name: 'Vaseline Gauze', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-171', name: 'ที่ขูดจี้', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-172', name: 'ปลอกจี้', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-173', name: 'แปรงสีฟัน', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-174', name: 'แผ่นสไลด์', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-175', name: 'ไม้จิ้มสี', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-176', name: 'ขวด Sterile', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-177', name: 'ไม้พันสำลี เล็ก-ใหญ่', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-178', name: 'ยางวง', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-179', name: 'ลูกสูบยาง C/S', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-180', name: 'สำลีลูกเล็ก', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-181', name: 'สำลีลูกใหญ่', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-182', name: 'หวี', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-183', name: 'Glass rod', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-184', name: 'UM.', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-185', name: 'ใบมีดตา 15 องศา', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-186', name: 'ใบมีดตา 2.8', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-187', name: 'ใบมีดตา 3.0', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-188', name: 'ไม้พันสำลีตา', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-189', name: 'ถุงน้ำตา', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-190', name: 'Eye Pad', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-gen-191', name: 'Eye Shield', category: 'อุปกรณ์ทั่วไป', active: true },
    // Existing 
    { id: 'eq-1', name: 'Army-Navy', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-2', name: 'Richardson', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-3', name: 'Deaver', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-4', name: 'Senn', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-5', name: 'Malleable retractor', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-6', name: 'Mosquito Forceps', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-7', name: 'Kelly Forceps', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-8', name: 'Crile Forceps', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-9', name: 'Kocher Forceps', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-10', name: 'Needle Holder', category: 'อุปกรณ์ทั่วไป', active: true },
    { id: 'eq-11', name: 'Towel Clip', category: 'อุปกรณ์ทั่วไป', active: true },
