    // ตู้ Neuro
    { id: 'eq-neuro-1', name: 'Bipolar forceps', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-2', name: 'Brain spatula (1ชิ้น/6ชิ้น)', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-3', name: 'Chinese Finger splint', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-4', name: 'Codman disp perforator', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-5', name: 'Dissection of hand', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-6', name: 'Flu cloth', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-7', name: 'Gigli saw handle + แผ่นรอง', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-8', name: 'Hand drill', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-9', name: 'Microsurgery Hand สีเงิน / สีฟ้า', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-10', name: 'Miniplate set 1.7 / 2.0', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-11', name: 'Self thyroid เล็ก / ใหญ่', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-12', name: 'Self thyroid หักได้', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-13', name: 'Set ต่อ Nerve', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-14', name: 'Skull tong', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-15', name: 'V-P Shunt handle', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-16', name: 'V-P Shunt passer (ไกด์ยาว)', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-17', name: 'เครื่องมือ hand (พ.มีนา)', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-18', name: 'ชุดหัว Burr / Twist drill', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-19', name: 'ดอกสว่าน', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-20', name: 'ใบเลื่อย', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-21', name: 'หัวกรอ 3 / 5 m.m.', category: 'ตู้ Neuro', active: true },
    { id: 'eq-neuro-22', name: 'หัวใบพาย', category: 'ตู้ Neuro', active: true },

    // ตู้ General
    { id: 'eq-genr-1', name: 'Abdominal เล็ก / กลาง', category: 'ตู้ General', active: true },
    { id: 'eq-genr-2', name: 'Allis สั้น / ยาว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-3', name: 'Army navy retractor', category: 'ตู้ General', active: true },
    { id: 'eq-genr-4', name: 'Arterial clamp ตรง / โค้ง', category: 'ตู้ General', active: true },
    { id: 'eq-genr-5', name: 'Babcock สั้น / ยาว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-6', name: 'Deep retractor สั้น / ยาว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-7', name: 'Deaver เล็ก / ใหญ่ / กลาง', category: 'ตู้ General', active: true },
    { id: 'eq-genr-8', name: 'Deaver หน้ากว้าง / sweet heart', category: 'ตู้ General', active: true },
    { id: 'eq-genr-9', name: 'Dilator rectum 18,14,10 ชิ้น', category: 'ตู้ General', active: true },
    { id: 'eq-genr-10', name: 'Intestinal clamps ตรง / โค้ง', category: 'ตู้ General', active: true },
    { id: 'eq-genr-11', name: 'Intestinal right angle', category: 'ตู้ General', active: true },
    { id: 'eq-genr-12', name: 'Kocher clamp โค้ง (4 ตัว)', category: 'ตู้ General', active: true },
    { id: 'eq-genr-13', name: 'Mosquito โค้ง (3 ตัว) , ตรง (3ตัว)', category: 'ตู้ General', active: true },
    { id: 'eq-genr-14', name: 'Pean curve ( 6ตัว )', category: 'ตู้ General', active: true },
    { id: 'eq-genr-15', name: 'Payr clamp 2 ตัว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-16', name: 'Procto ที่ถ่างก้น', category: 'ตู้ General', active: true },
    { id: 'eq-genr-17', name: 'Procto ธรรมดา / ผ่ากลาง', category: 'ตู้ General', active: true },
    { id: 'eq-genr-18', name: 'Purse string clamp', category: 'ตู้ General', active: true },
    { id: 'eq-genr-19', name: 'Retractor กาบกล้วย', category: 'ตู้ General', active: true },
    { id: 'eq-genr-20', name: 'Retractor เจาะคอ', category: 'ตู้ General', active: true },
    { id: 'eq-genr-21', name: 'Right angle 4 ตัว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-22', name: 'Saint Mark ธรรมดา /ปลายยาวงอ', category: 'ตู้ General', active: true },
    { id: 'eq-genr-23', name: 'Self ศัลย์ 9 ชิ้น', category: 'ตู้ General', active: true },
    { id: 'eq-genr-24', name: 'Spatula มีรู', category: 'ตู้ General', active: true },
    { id: 'eq-genr-25', name: 'Sponge holder ตรง / โค้ง 2 ตัว', category: 'ตู้ General', active: true },
    { id: 'eq-genr-26', name: 'Tonsil clamp 2 ตัว ปลายแหลม, ธรรมดา', category: 'ตู้ General', active: true },
    // Existing General
    { id: 'eq-40', name: 'Scalpel Handle #3 / #4 (ด้ามมีดผ่าตัด)', category: 'ตู้ General', active: true },
    { id: 'eq-41', name: 'Electrocautery Pencil (ด้ามจี้ไฟฟ้า)', category: 'ตู้ General', active: true },
    { id: 'eq-42', name: 'Harmonic Scalpel Handpiece', category: 'ตู้ General', active: true },
    { id: 'eq-43', name: 'Skin Stapler', category: 'ตู้ General', active: true },
    { id: 'eq-44', name: 'Suction Tip (Yankauer / Poole)', category: 'ตู้ General', active: true },
