    // ตู้ Ortho
    { id: 'eq-ortho-1', name: 'Acetabulum Clamp เล็ก / ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-2', name: 'Aiming Device / Bone Biopsy', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-3', name: 'Bending Iron (ดัดplateมือ)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-4', name: 'Bone Clamp เล็ก/ กลาง / ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-5', name: 'Bone Cutter เล็ก / ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-6', name: 'Bone Hook / Bone Skid', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-7', name: 'Bone Rongeur Beyer / Stille', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-8', name: 'Bone Rongeur Ruskin / angle stille', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-9', name: 'Broken screw (ชุด)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-10', name: 'Cartilage set', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-11', name: 'Cervical dissector (Bone graft 7 ชิ้น)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-12', name: 'Cervical Spreader', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-13', name: 'Cloward (14ชิ้น)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-14', name: 'Cobb 9 นิ้ว ด้ามไม้ / ด้ามเหล็ก', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-15', name: 'Cobb ยาว 11นิ้ว 10 / 18 mm.', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-16', name: 'Curette (ฟันหนู 13mm/8.5mm)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-17', name: 'Curette No.', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-18', name: 'Curette spine 3 ชิ้น ตรง /โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-19', name: 'Curette ตรง no. 3 (พ.สุวิโชติ)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-20', name: 'Depth Gauge for 3.5 / 4.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-21', name: 'Drill bit 1.1/1.5 /2.0 /2.5 /2.7', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-22', name: 'Drill bit 3.2/3.5/4.5/6.0', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-23', name: 'Drill sleeve 2.5/3.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-24', name: 'Freer (Penfield) สั้น /ยาว', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-25', name: 'Freer + ด้ามมีด No.7', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-26', name: 'Hibbs retractor เล็ก / ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-27', name: 'Hohmann Ret gen / โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-28', name: 'Impactor ด้ามเหล็ก / ด้ามไม้', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-29', name: 'Jacob Chuck / Telescope', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-30', name: 'Kerrison 2 / 3/ 4 /5 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-31', name: 'Kocher Clamp ตรง 1ตัว', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-32', name: 'Macdonald มีรู /ไม่มีรู', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-33', name: 'Narrow plate (ห่อ Ok.)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-34', name: 'Nerve hook / Nerve Root โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-35', name: 'Osteotome (สิ่ว)โค้ง/ตรง........ mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-36', name: 'Periosteum + small hohmann', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-37', name: 'Periosteum ตรง /ด้ามเหล็ก', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-38', name: 'Protect sleeve', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-39', name: 'Reduction forceps / with point', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-40', name: 'Screw driver 3.5 / 4.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-41', name: 'Screw driver shaft 3.5 / 4.6', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-42', name: 'Self 8 ชิ้น / Self Laminectomy', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-43', name: 'Small hohmann', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-44', name: 'Spinal probe /Sound', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-45', name: 'Spinal Retractor /Staple set', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-46', name: 'Tap 2.7/3.5/4.0/4.5/6.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-47', name: 'T-handle', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-48', name: 'Towel clip', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-49', name: 'T-wrench สั้น / ยาว /หักได้', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-50', name: 'Universal chuck key', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-51', name: 'Universal drill sleeve 2.5/3.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-52', name: 'Universal drill sleeve 6.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-53', name: 'Wire cutter เล็ก / ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-54', name: 'Wire passer เล็ก /ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-55', name: 'ชุด Drill bit 4.5', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-56', name: 'Lowman clamp', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-57', name: 'Ankle Compressor (foot)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-58', name: 'block cement เข่า/ สะโพก', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-59', name: 'block cement ทำ genta bead', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-60', name: 'Calcaneous bone spreader spatula', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-61', name: 'Chisel angle 15\' / 7 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-62', name: 'DCP drill sleeve (เขียวเหลือง)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-63', name: 'Femoral retractor', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-64', name: 'Flag splitter', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-65', name: 'Gelpi ret. / Gelpi ret. ขายาว', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-66', name: 'Gouge ตรง /โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-67', name: 'Guide wire for c-spine', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-68', name: 'K-wire spreader (foot)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-69', name: 'Lamina spreader', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-70', name: 'Meyerding Ret.(พ.อาทิตย์ ม.)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-71', name: 'Mikimon self retaining (Self พ.สุวิโชติ)', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-72', name: 'Milligant discectomy', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-73', name: 'Osteotome ตรง 7 มม.ยาว 16.5"', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-74', name: 'Pelvic reduction clamp', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-75', name: 'Reposition forceps เล็ก /ใหญ่', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-76', name: 'Retractor ขาเดียว/ พ.เกษม', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-77', name: 'Reverse curette 6 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-78', name: 'William micro discectomy 1x5 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-79', name: 'William micro discectomy 1x7 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-80', name: 'William micro discectomy 2x5 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-81', name: 'ค้อน 300/ 350/500/700/900', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-82', name: 'คีมปากแบน / แหลม', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-83', name: 'คีมล็อค', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-84', name: 'ชุด C-Spine ( 7 ชิ้น )', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-85', name: 'ชุด ใส่ Plate นิ้ว ( 12 ชิ้น )', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-86', name: 'ตัวจับหมุด', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-87', name: 'ตัวย้ำ K-wire', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-88', name: 'ถ้วย Cement', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-89', name: 'ถุง Scope / ถุง X-ray', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-90', name: 'ถุง Stockinette Hip/Knee', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-91', name: 'ถุงกล้อง liga', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-92', name: 'ที่จี้เส้นประสาท พ.สุรศักดิ์', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-93', name: 'ที่ดัด K-wire + Impactor', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-94', name: 'ที่ดัด-ตัด K-wire /คีมดัด K-wire', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-95', name: 'ใบเลื่อย No…..', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-96', name: 'ประแจ No.8 / 11 /10', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-97', name: 'ไม้บรรทัด เหล็ก /สั้น / ยาว', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-98', name: 'ยางเทาฟ้า 6/ 4 / 3', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-99', name: 'สาย Small air drill', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-100', name: 'สิ่ว ตรง,โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-101', name: 'สิ่ว 9", 12 / 6 mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-102', name: 'สิ่วด้ามเหล็ก 11", 25mm ตรง/ โค้ง', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-103', name: 'สิ่วตรงยาว (ด้ามไม้)............... mm', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-104', name: 'ห่อ K-wire / Steinmann pin', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-105', name: 'หัว Sagittal saw', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-106', name: 'หัวต่อ reamer ของ Aesculap drill', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-107', name: 'หัวต่อ saw ของ Aesculap drill', category: 'ตู้ Ortho', active: true },
    { id: 'eq-ortho-108', name: 'เหล็ก X-ray', category: 'ตู้ Ortho', active: true },
