    // ตู้ Plastic
    { id: 'eq-plas-1', name: 'Deep retractor ยาว (in-out) คู่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-2', name: 'Deep retractor ยาว (out) 1 ตัว', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-3', name: 'Pig tail', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-4', name: 'Set orthognathic (ทันตกรรม)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-5', name: 'Setถอนฟัน 34 ชิ้น', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-6', name: 'Tongue blade', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-7', name: 'Towel clip พ.ธนพงษ์', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-8', name: 'Wire suspension', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-9', name: 'Wire twister', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-10', name: 'Senn retractor', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-11', name: 'กรรไกร Mayo 6", ยาว 9"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-12', name: 'กรรไกรตัดลวด', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-13', name: 'กรรไกรตัดไหม สั้น 6", ยาว 8" 9"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-14', name: 'กระจกส่องฟัน', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-15', name: 'กล่องลวด Plastic', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-16', name: 'เข็มร้อยลวด', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-17', name: 'ด้ามมีดกร๊าฟ', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-18', name: 'ด้ามมีดเล็กสั้น No.3 / 4 / 7 / 3L', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-19', name: 'ที่งัดจมูก 4 ชิ้น', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-20', name: 'ที่ดัด Plate พ.พัลลภา', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-21', name: 'ที่แยงท่อน้ำตา', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-22', name: 'ไม้กดลิ้น', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-23', name: 'ไม้กร๊าฟ', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-24', name: 'วงเวียน', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-25', name: 'สายลม Mini Air drill', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-26', name: 'หัว Drill of Mini Air drill', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-27', name: 'หัวจี้ยาว', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-28', name: 'หัวต่อ Suction เหล็ก', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-29', name: 'หัวยิง K-wire', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-30', name: 'Bayonet forceps', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-31', name: 'Bone hook เล็ก / ใหญ่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-32', name: 'Bulldog clamp 3 ตัว', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-33', name: 'Dent Heart เล็ก / ใหญ่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-34', name: 'Dermatel 2 ตัว', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-35', name: 'Dingman', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-36', name: 'Double hook / Skin hook', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-37', name: 'Duhamel', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-38', name: 'Forceps 7" (tooth,non-tooth) หนา,บาง', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-39', name: 'Hand piece of Mini Air drill', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-40', name: 'Jeweler forceps angle', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-41', name: 'Jeweler forceps ตรง', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-42', name: 'Kocher dissector', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-43', name: 'Long Forceps 10" (tooth,non-tooth), 12"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-44', name: 'Mandible reduction', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-45', name: 'Maxillary elevator', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-46', name: 'Metzenbaum 10"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-47', name: 'Metzenbaum 6"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-48', name: 'Metzenbaum 7"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-49', name: 'Metzenbaum 8"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-50', name: 'Metzenbaum 9"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-51', name: 'Metzenbaum ปลายแหลมเล็ก', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-52', name: 'Micro forceps', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-53', name: 'Micro Needle', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-54', name: 'Micro scissors', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-55', name: 'Mouth gag', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-56', name: 'Mouth prop (น้ำตาล)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-57', name: 'Nasal retractor', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-58', name: 'Nasal Volkman', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-59', name: 'Needle biopsy 3 ตัว', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-60', name: 'Needle Bx. 5 ชิ้น', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-61', name: 'Needle holder 10" (ปลายงอ/พ.เขียว)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-62', name: 'Needle จับลวด', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-63', name: 'Needle ด้ามทอง 10"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-64', name: 'Needle ด้ามทอง 5"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-65', name: 'Needle ด้ามทอง 6"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-66', name: 'Needle ด้ามทอง 7"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-67', name: 'Needle ด้ามทอง 8"', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-68', name: 'Periosteum + Zygoma', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-69', name: 'Periosteum + ตะไบ', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-70', name: 'Periosteum ORIF', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-71', name: 'Periosteum ฝนจมูก', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-72', name: 'Periosteum เล็ก', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-73', name: 'Probe ธรรมดา / หางปลา', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-74', name: 'Rib Retractor (พ.พงษ์สิทธิ์)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-75', name: 'Screw driver 2.0 เล็ก / ใหญ่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-76', name: 'Screw driver 1.7 / 1.6 กล่องใหญ่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-77', name: 'Septum knife', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-78', name: 'Set ถอนฟัน 7 ชิ้น', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-79', name: 'Short forceps (tooth-non,tooth)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-80', name: 'Suction tube 8/10/12/15', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-81', name: 'Suction หลายรู เล็ก /ใหญ่', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-82', name: 'Trocar gallbladder+guide', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-83', name: 'Vascular approximator', category: 'ตู้ Plastic', active: true },
    { id: 'eq-plas-84', name: 'Volkman 2 ตัว', category: 'ตู้ Plastic', active: true },
    // Existing Plastic
    { id: 'eq-50', name: 'Micro Scissors (กรรไกรตกแต่งศัลยกรรม)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-51', name: 'Adson Tooth Forceps (1x2)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-52', name: 'Plastic Needle Holder (Castroviejo)', category: 'ตู้ Plastic', active: true },
    { id: 'eq-53', name: 'Skin Hook Retractor', category: 'ตู้ Plastic', active: true },
    { id: 'eq-54', name: 'Freer Elevator', category: 'ตู้ Plastic', active: true },

    // ตู้ Ob-gyn
    { id: 'eq-obgyn-1', name: 'A-P retractor', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-2', name: 'Curette suction', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-3', name: 'Curettage สูติ 10 ชิ้น , 17 ชิ้น', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-4', name: 'Doyen retractor', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-5', name: 'Forceps สูติ', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-6', name: 'Heaney clamp', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-7', name: 'Hook เกี่ยว tube', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-8', name: 'Posterior retractor', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-9', name: 'Retractor พ.พัลลภ 3 ชิ้น', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-10', name: 'Russian 7", 9"', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-11', name: 'Silver cath สั้น / ยาว', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-12', name: 'Speculum', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-13', name: 'Tenaculum', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-14', name: 'Uterine clamp', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-15', name: 'Uterine elevator', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-16', name: 'Wertheim angie', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-17', name: 'อุปกรณ์ฉีดสีทาง Vagina 1', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-18', name: 'Myoma Screw', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-19', name: 'Curette สูติ 10 ชิ้น', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-20', name: 'Breisky Retractor', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-obgyn-21', name: 'Self TAH', category: 'ตู้ Ob-gyn', active: true },
    // Existing Ob-gyn
    { id: 'eq-60', name: 'Set ผ่าตัดทำคลอด C-Section', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-61', name: 'Vaginal Speculum (Graves/Pederson)', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-62', name: 'Tenaculum Forceps', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-63', name: 'Uterine Sound', category: 'ตู้ Ob-gyn', active: true },
    { id: 'eq-64', name: 'Ovum Forceps / Curette', category: 'ตู้ Ob-gyn', active: true },

    // ตู้ Uro + Ob-gyn
    { id: 'eq-uro-1', name: 'Dilator urethra ตรง 9,13,14', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-2', name: 'Gelpi retractor 1 คู่ โค้ง', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-3', name: 'Kidney stone 13 ชิ้น', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-4', name: 'Micro needle URO ( 1 คู่ )', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-5', name: 'Micro scissor ตรง / โค้ง', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-6', name: 'Mixter right angle 2 ตัว', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-7', name: 'Needle 5"', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-8', name: 'Pedicle clamps 4 ตัว', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-9', name: 'Periosteum+Rib shear', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-10', name: 'Retractor จิ๋ว สั้น / ยาว', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-11', name: 'Rib cutter', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-12', name: 'Stamey needle 3 อัน', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-13', name: 'Suction tip R.17/Suction plastic', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-14', name: 'Stone forceps', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-15', name: 'Turner Warwick 1 คู่', category: 'ตู้ Uro + Ob-gyn', active: true },
    { id: 'eq-uro-16', name: 'ไม้บรรทัด URO', category: 'ตู้ Uro + Ob-gyn', active: true }
